@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package valoeghese.originsgacha.screens;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
